project_id = "unatnldzcewjtfpumkzp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.notify-new-lead]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
